model:
  type: resnet56
dataset: cifar10
aug: fa_reduced_cifar10
cutout: 16
batch: 128
epoch: 200
lr: 0.1
lr_schedule:
  type: 'multistep'
  steps:
    - 100
    - 150
optimizer:
  type: sgd
  nesterov: False
  decay: 0.0002
  ema: 0
  clip: 0
